class Scene {
    constructor(id, title, char1Img, char2Img, bgImg, text, options, forceScene) {
        this.char1Img = char1Img;
        this.char2Img = char2Img;
        this.bgImg = bgImg;
        this.text = text;
        this.id = id;
        this.title = title;
        this.options = options;
        this.forceScene = forceScene;
        this.currSceneDia = 0;
    }
    
    id;
    title;
    char1Img;
    char2Img;
    bgImg;
    text;
    options;
    currSceneDia;
    forceScene;
}



//give each new scene and id, both char images and all text options
let start = new Scene(1, "START_MAIN", "./media/nonochar1.png", "", "./media/1start.png", ["Welcome to Ramen Quest! To start, hit the next button above!", "Keys jingle from outside of the door. The soft clicks of them turning into the lock signal the arrival of the apartment's resident. Nono walks in, the apartment is dark but she doesn’t care, she’s on a mission.", "She tosses her stuff down onto the couch and heads straight to the kitchen. She starts for a moment, looking, scanning the shelves and cabinets. Where is it? Where did it go?", "Slight panic but mostly anger starts to well up inside of her. She heads down the hallway, to her roommates room. She doesn’t bother to knock, but instead just shoves the door open.", 
"The dark room is lit only by the glow of two computer monitors, one with some anime on it, the other some game. The figure in the chair at the desk startles and spins around.", "There, placed in her hands, is the thing Nono was searching for. Momiji looks startled, but slurps up the last of the contents of the cup noodle she has in her hands.", "“You ate the last one? Really?”, Nono says, sighing loudly. “What, you weren't here. I bought them last time anyway”, Momiji says shrugging.", "“Yeah but that doesn’t mean I wouldn’t be, ugh. Now I’ve gotta go get more.”, Nono simply turns back around and closes the door. “Damn, what time is it anywa-, Oh god damn it”", "She pulls out her phone as she talks to herself, and looks at it panicked. “The store closes at 10, I’ve got like, 30 minutes to get there. Man this sucks.”", "She grabs her coat back off of the couch and heads back to the door. Her mission is set. She must reach the convenience store before it closes. Nono’s quest for ramen has begun."]);

let neighbor = new Scene(2, "START_NEIGHBOR", "./media/nonochar1.png", "./media/neigh0.png", "./media/2neigh.png", ["Nono closes the door after having just opened it, entering the night yet again. The night was still, and a tad chilly. The clear sky shone with the stars of the universe but tonight, none of that mattered.", "All that mattered was the sodium filled treat awaiting Nono at the store. Taking a deep breath of the crisp night air, she turned to start down the stairs to the road below.", "...But an obstacle immediately presented itself, or rather herself...", "“Oh Nono dear! It's good to see you!”, It was Mrs Sachi, the very kind but VERY talkative next door neighbor. “Oh Mrs Sachi, how are you?”, Nono asked out of politeness.", "She really couldn't care less, she saw Mrs Sachi nearly everyday, she knew how she was. She was in a hurry, Mrs Sachi could prove an able opponent at stopping her from getting to the store on time.", "...She had to navigate this carefully. “Oh I’m doing fine dear, where are you headed at this time? Didn’t you just get home?”"], [{text: "“I’m heading to the store”", optScene: 3}, {text: "“Just going out for a stroll”", optScene: 4}, {text: "“There was a new thing that came out”", optScene: 5}]);

let neighborOptn1 = new Scene(3, "NEIGHTBOR_OPTION1", "./media/nonochar1.png", "./media/neigh1.png", "./media/3neighopt1.png", ["", "“Well, Momiji ate the last of our ramen, so I’ve gotta run and buy some more since she bought them last time”, she says, surprisingly truthfully. “Oh dear, what an inconvenience...", "...You know my husband worked at that ramen shop for-”. Oh no, wrong choice, she starts going on and on about her husband's old ramen shop, the ramen shop's cousins and what each aunt and uncle did last Tuesday...", "She doesn’t stop talking either, it’s almost impressive how someone can talk for this long and say so little. Eyes glazed over, Nono snaps back to reality for a second, Mrs Sachi still waffling on and on...", "She looks at her phone and her eyes widen, she’s been here for 5 minutes already. “Ah sorry Mrs Sachi but, I really should get going. It was nice chatting to you, bye!”", "...She quickly says, before brushing past Mrs Sachi and quickly half running down the stairs to escape the chatty neighbors grasp."], [], 6);

let neighborOptn2 = new Scene(4, "NEIGHTBOR_OPTION2", "./media/nonochar1.png", "./media/neigh2.png", "./media/4neighopt2.png", ["", "“Just going out for a stroll, what are you up to Mrs Sachi?”, Nono replies rather casually. “Oh just taking in the night air myself, you know how I love the city at night”, Mrs Sachi replies...", "Nono looks out from their 2nd floor apartment balcony walkway thing. The view from here isn’t fantastic, it's just the local park bureau office across the street, its windows dark for the evening...", "...everyone having gone home long ago. If you look up, however, the real show can be seen. The lights of central Tokyo shine all around. The skyscrapers can be seen in their full glory on this cloudless night...", "The stiff breeze blows a gust by as an airplane flies overhead, flicking its lights in warning to any that would draw too near. A car passing by down below startles Nono back to reality...", "...and she notices Mrs Sachi isn’t out here anymore, hearing the click of her door closing. She must have been talking to her while she spaced out and gotten bored.", "...Nono heads down the stairs out onto the street, to the ramen waiting for her."], [], 6);

let neighborOptn3 = new Scene(5, "NEIGHTBOR_OPTION3", "./media/nonochar1.png", "./media/neigh3.png", "./media/5neighopt3.png", ["", "“Oh there’s a release of a new game or model or something, I forget. Anyways I’ve gotta get going before they run out.”, Nono says quickly, trying to hurry the conversation along...", "“Oh you and those games again? You know I read that-”, Mrs Sachi starts, but Nono starts talking, an idea quickly forming to get Mrs Sachi to go away. “It’s actually the new perfect master grade...", "...of the RX-28-42-2 EG Gold edition with the additional gold cano-”, she starts rattling off whatever jargon she can think of, and it works. Mrs. Sachi waves a hand at her...", "“Oh no no, it’s fine dear, you don’t need to explain it to me. Go on and get your um, whatever it is.”, she gives her a kind of forced smile. Nono successfully out-talked Msr Sachi, a crowning achievement to be sure.", "She gives Mrs Sachi a goodbye wave and heads down the stairs and on to the street below."], [], 6);

let street = new Scene(6, "START_STREET", "./media/nonochar1.png", "", "./media/6street.png", ["","Down here on the sidewalk, the street is quiet tonight. A few cars pass by every now and then as Nono walks her way in the direction of the store. The slight chill and the stiff breeze are reminders that fall is here...", "...As one particular gust sends a plethora of leaves flying, spiraling and scattering about. Shaking her head to clear the distractions, Nono comes up to the 4 way crossing.", "The more direct way would be to keep heading straight, but there are ways to get there going left or right, that may take less time depending on what lies ahead. Which direction do you choose?"]);

let yankee = new Scene(7, "START_YANKEE", "./media/nonochar1.png", "./media/yankee1.png", "./media/7yank.png", ["","Deciding to take the more direct route, Nono heads on down the street straight ahead. Walking down the brightly lit street for a while, an interesting scene unfolds before her...", "...She stops to watch the altercation. Two guys in black leather jackets, with slicked back hair styles stood on opposite ends of the street. They stood, staring one another down. Both not moving a muscle...", "...It seemed that everyone on that small street stopped and watched too. An old couple paused, their shopping in hand, a mother grabbed her child close, a group of teenagers hid behind a restaurant sign...", "...They poke their heads over it to watch whatever is about to go down. The street is now vacated, everyone is hiding off to the side as the two men stand, looking at one another.", " From one of the alley ways, another man walks out, wearing the same git up as the two guys standing off. His hair styled in a pompadour, his leather jacket gleaming in the nights lights...", "He carries a stereo with him, which he places down on the ground in the middle of the street. He looks at the two guys, nodding at each one in turn, and turns on the stereo.",".............................................................." , "Rockabilly music starts blasting through the narrow street, and the two men start shuffle dancing towards each other. This must be a dance off. They both move to the middle of the street and start dancing at each other.", "Suddenly, more leather jacketed guys come from other various directions until there’s at least 10 guys all grooving at each other in the middle of the street to Jail House Rock.", "Nono stands there for a bit, more in shock than anything. One of the onlookers standing next to her just shrugs, “They do this about once a week, I’m kinda used to it”...", "...Nono just sighs, and starts back on her way down the street."]);

let tourist = new Scene(8, "START_TOURIST", "./media/nonochar1.png", "./media/tour0.png", "./media/8tour.png", ["After the shock of the dancing street thugs, Nono kept on walking down the street, a bit confused but also kind of annoyed that she just wasted all that time standing there.", "Carrying on for another few minutes, the glow of the convenience store sign comes into view around the corner. The sweet glow of the 8/12 caught her eye with a sparkle, the ramen was close...", "Lost in her thoughts of noodles and broth, Nono didn’t hear the person approaching her, “Excuse a me lady, may you understand?”. Nono turns around and sees the worst obstacle yet.", "Baseball cap, Hawaiian shirt, cargo shorts, a huge rolling suitcase. The worst of beasts, a tourist, and one that seemed lost at that. “Can you know the what I saying?”, he asked Nono. This could take a while if she wasn’t quick..."], [{text: "“Sorry I don’t understand”", optScene: 9}, {text: "“I am the good of the knowing of your words”", optScene: 10}, {text: "“Yeah, I think so?”", optScene: 11}]);

let touristOptn1 = new Scene(9, "TOURIST_OPTION1", "./media/nonochar1.png", "./media/tour1.png", "./media/9touropt1.png", ["", "“Um, sorry buddy but I’ve got no idea what you just said, I really need to get going”, Nono quickly says, trying to walk away from the lost tourist. “Ah but who cans of helping near?”...", "...He says following her, hand outstretched in need. It’s then that Nono has an idea. She can kill two birds with one stone. She turns around and motions to the guy, beckoning him to follow her...", "“Hey you, come with me, this way.”. Looking a bit confused, the guy follows along. Nono doesn’t even look back at him and just walks straight on...", "...Straight on to the convenience store, its neon glow a lighthouse beacon for the lost ships of the hungry and those needing to do a bit of shopping."], [], 12);

let touristOptn2 = new Scene(10, "TOURIST_OPTION2", "./media/nonochar1.png", "./media/tour2.png", "./media/10touropt2.png", ["", "Being a self proclaimed master of linguistics, Nono replies back, “Ah yes the wordings you of saying good sense making. Going where you are going trying to?”. The tourist just stands there, looking even more confused.", "“W-whats?”, they say, dumbfounded by what ever Nono just spewed out of her mouth. He starts looking around for literally anyone else to talk to. He puts his hands up and says, “Ah sorry, no understanding. It fine, it fine.”...", "...And he quickly tries to run off, not wanting to deal with this anymore, his rolly suitcase clattering on the sidewalk as he searches for someone else to help...", "“Huh, guess that… worked…?”, Nono says to herself, a bit confused as to how her expert command of language had just failed her but having sent the tourist away, it was still a victory.", "That being dealt with, she heads on towards the convenience store. Its neon glow is a lighthouse beacon for the lost ships of the hungry and those needing to do a bit of shopping."], [], 12);

let touristOptn3 = new Scene(11, "TOURIST_OPTION3", "./media/nonochar1.png", "./media/tour3.png", "./media/11touropt3.png", ["", "Nono looks confused for a second, trying to process whatever he just said. “Oh, yeah, I think I know what you just said. Um…”, she looks around, looking for someone that might be able to help them.", "Not seeing any immediate help, as everyone else on the street is avoiding them like the plague, she sighs. “Are you… lost or something? Need directions?”, she asks, hoping he understands her.", "“Ah, yes yes. Lost!”, he pulls out a fold out tourist map of the city, pointing at it and saying, “B-bus?”, he shakes his head, “No no, train, yes train place?”, he says rather enthusiastically.", "“Oh you need to find the train station?”, she looks over the map and points to the nearest train station, “Here, right here is where you should go.”. The tourist looks at the map intently.", "He may not have understood her words but he understood her intent. He gives her a large smile and says, “Many thanks yous!.”...", "...He starts heading off towards the opposite direction, heading towards the convenience store instead. “W-what… okay whatever”, she sighs...", "Deciding to follow after him, but not to speak with him, she heads towards the store herself. Its neon glow is a lighthouse beacon for the lost ships of the hungry and those needing to do a bit of shopping."], [], 12);

let ending = new Scene(12, "START_ENDING", "./media/nonochar1.png", "./media/ramen12.png", "./media/12end.png", ["", "Before Nono stands the great double sliding doors of the convenience store. Beyond these barriers lay the vast wealth of the hungry and cheap of pocket.", "The shelves are lined with snacks of every type, reasonably priced for your purchasing pleasure. She looks up at the glowing sign and into the brightly lit interior, readying herself for the crisp air conditioned air that awaits...", "...inside, and the wafting smell of the cooked food section. *DING DING DONG DING*. The melody plays as she walks forward, causing the sliding doors to part ways and grant her entrance to this great realm of...", "...confectionaries. She knows exactly what she wants, she doesnt stop to look at the chips, or candy bars, she heads right to the back wall. The most magnificent sight is here, a wall of nothing but cup ramen of every kind.", "5 shelves from floor to above head height of every sea food, beef, chicken or otherwise powdered sodium rich noodles you could want. Surprisingly this entire time she was on the way here, she hadn’t thought about...", "...what kind of ramen to even buy. Looking over the shelves as some pop song blared in the background, she made her choices and headed to the register. Of course, she was buying for the week...", "...so she grabbed a selection of different noodles to keep her and her roommate fed for the week. Checking out and heading back out of those sliding doors, she notices something on the wall...", "“Open 24 hours”, the sign proudly exclaims. “R-really… I just rushed over here for no reason?”, she sighs. Laughing a bit she shrugs, no longer caring.", "Heading home, past the tourist who was at the counter, asking the poor cashier for help, past the dancing guys still in the center of the street, and finally reaching her apartment door, with no Mrs Sachi in sight...", "She heads back in, tossing her coat down on the sofa and heading right to the kitchen. She finally gets to crack open the seal on the noodles she had hoped to have eaten an hour ago, and finally settles down.", "The quest for ramen has come to a close. Thanks for playing!:D"]);

let allScenes = [];
allScenes.push(start);
allScenes.push(neighbor);
allScenes.push(neighborOptn1);
allScenes.push(neighborOptn2);
allScenes.push(neighborOptn3);
allScenes.push(street);
allScenes.push(yankee);
allScenes.push(tourist);
allScenes.push(touristOptn1);
allScenes.push(touristOptn2);
allScenes.push(touristOptn3);
allScenes.push(ending);

export var sceneList = allScenes;
